# Generated by Django 3.2 on 2021-06-07 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='profiles/default.jpg', upload_to='media/profiles/')),
                ('height', models.FloatField(default=170.0)),
                ('weight', models.FloatField(default=60.0)),
                ('weight_goal', models.FloatField(default=70.0)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=('F', 'Female'), max_length=9)),
                ('week_frequency', models.CharField(choices=[('3x', '3 Times a Week'), ('4x', '4 Times a Week'), ('5x', '5 Times a Week'), ('6x', '6 Times a Week')], default=('3x', '3 Times a Week'), max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
