# Generated by Django 3.2 on 2021-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='media/profiles/'),
        ),
    ]
