# Generated by Django 3.2.4 on 2021-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_alter_event_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_diets',
            field=models.ManyToManyField(to='dashboards.DietPlan'),
        ),
    ]
