# Generated by Django 3.2.4 on 2021-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_selected_diets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
