# Generated by Django 3.2.4 on 2021-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0032_alter_event_date'),
        ('users', '0003_auto_20210613_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_diets',
            field=models.ManyToManyField(null=True, to='dashboards.DietPlan'),
        ),
    ]
