# Generated by Django 3.2.4 on 2021-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0033_alter_event_date'),
        ('users', '0004_alter_profile_selected_diets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_diets',
            field=models.ManyToManyField(blank=True, to='dashboards.DietPlan'),
        ),
    ]
