# Generated by Django 3.2 on 2021-06-04 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='week_frequency',
            field=models.CharField(choices=[('3x', '3 Times a Week'), ('4x', '4 Times a Week'), ('5x', '5 Times a Week'), ('6x', '6 Times a Week')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
