# Generated by Django 3.2 on 2021-06-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
