# Generated by Django 3.2 on 2021-06-11 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_adminnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotes',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 9, 57, 49, 386718)),
        ),
    ]
