# Generated by Django 3.2.4 on 2021-06-12 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ends_work_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 16, 14, 41, 788572)),
        ),
        migrations.AddField(
            model_name='workspace',
            name='starts_work_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 16, 14, 41, 788572)),
        ),
        migrations.AlterField(
            model_name='adminnotes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 16, 14, 41, 788572)),
        ),
    ]
