# Generated by Django 3.2 on 2021-06-07 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='diets/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 21, 40, 23, 810649)),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='events/default.jpg', upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='routines/'),
        ),
    ]
