# Generated by Django 3.2 on 2021-06-04 18:30

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='img',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routime_dscr',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routime_name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_dscr',
            field=models.TextField(default=datetime.datetime(2021, 6, 4, 18, 30, 31, 849589, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
