# Generated by Django 3.2 on 2021-06-07 16:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0002_auto_20210604_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='diet_dscr',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='diet_name',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_dscr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_dscr',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_thumbnail',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routine_dscr',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routine_name',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='thumbnail',
            field=models.ImageField(default='media/diets/default.jpg', upload_to='media/diets/'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 18, 59, 27, 338513)),
        ),
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='media/events/default.jpg', upload_to='media/events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='exercise',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='routine',
            field=models.ManyToManyField(to='dashboards.Routine'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='routine',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routine',
            name='thumbnail',
            field=models.ImageField(default='media/routines/default.jpg', upload_to='media/routines/'),
        ),
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
