# Generated by Django 3.2 on 2021-06-07 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20210607_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 21, 43, 26, 685708)),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default='events/default.jpg', upload_to='events/'),
        ),
    ]
