# Generated by Django 3.2 on 2021-06-07 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20210607_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='thumbnail',
            field=models.ImageField(default='diets/default.jpg', upload_to='diets/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 21, 44, 13, 877486)),
        ),
        migrations.AlterField(
            model_name='routine',
            name='thumbnail',
            field=models.ImageField(default='routines/default.jpg', upload_to='routines/'),
        ),
    ]
