# Generated by Django 3.2 on 2021-06-08 13:33

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20210607_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thurday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default=('mon', 'Monday'), max_length=27),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 8, 15, 33, 35, 310326)),
        ),
    ]
