# Generated by Django 3.2 on 2021-06-10 11:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0011_auto_20210610_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='owner',
        ),
        migrations.AddField(
            model_name='exercise',
            name='selected_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routine',
            name='selected_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 13, 14, 55, 541545)),
        ),
    ]
