# Generated by Django 3.2 on 2021-06-10 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_auto_20210610_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 13, 16, 59, 346890)),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
