# Generated by Django 3.2.4 on 2021-06-12 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 12, 15, 38, 27, 724647)),
        ),
        migrations.AlterField(
            model_name='routine',
            name='days',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
