# Generated by Django 3.2.4 on 2021-06-13 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0025_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='routine',
        ),
        migrations.AddField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(to='dashboards.Exercise'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 12, 54, 54, 252764)),
        ),
    ]
