# Generated by Django 3.2.4 on 2021-06-13 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 17, 38, 16, 732356)),
        ),
    ]
