# Generated by Django 3.2.4 on 2021-06-13 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_auto_20210613_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='age',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 17, 39, 11, 889604)),
        ),
    ]
